name: Jesse Cohen
favicon: null
layout_spectrum: 0.55361
typography_spectrum: 0.55778
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.46813045581802726
  lightness: 0.375
  saturation: 0.75
  rhythmicContrast: 0.75
purpose: []
