name: Jesse Cohen
favicon: null
layout_spectrum: 0.31468253349885345
typography_spectrum: 0.55778
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.46813045581802726
  lightness: 0.5399972798768431
  saturation: 0.2077372563071549
  rhythmicContrast: 0.5773391681723297
purpose: []
